<a href="https://colab.research.google.com/github/rana6-12/-lab1-ITI/blob/main/Lab_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1**-**Import** **Numpy** & **Print** **Version**

In [2]:
import numpy as np;


In [3]:
print(np.__version__);

2.0.2


**2-# Define a list of numeric values & # Convert the list to a NumPy array**

In [4]:
# Define a list of numeric values
my_list = [1, 2, 3, 4, 5]

# Convert the list to a NumPy array
my_array = np.array(my_list)

# Print the array
print(my_array)

[1 2 3 4 5]


**3- Create a null vector of size** **9**

In [5]:
# Create a null vector of size 9
null_vector = np.zeros(9)

# Print the null vector
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0.]


**4. How to find the memory size of any array**

In [6]:
import numpy as np

# Create a sample array
my_array = np.array([[1, 2, 3], [4, 5, 6]])

# Get the number of elements
num_elements = my_array.size

# Get the size of each element in bytes
element_size = my_array.itemsize

# Calculate the total memory size in bytes
memory_size = num_elements * element_size

print(f"The array:\n{my_array}")
print(f"Number of elements: {num_elements}")
print(f"Size of each element (bytes): {element_size}")
print(f"Total memory size (bytes): {memory_size}")

The array:
[[1 2 3]
 [4 5 6]]
Number of elements: 6
Size of each element (bytes): 8
Total memory size (bytes): 48


5-** How to get the documentation of the numpy add function from the command line?**

In [7]:
import numpy as np

# Using the help() function
help(np.add)

# Using the ? magic command
# ?np.add

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retai

**6-6. Create a null vector of size 12 but the sixth value which is 1

In [8]:
import numpy as np

# Create a null vector of size 12
null_vector = np.zeros(12)

# Set the sixth value to 1 (index 5 since it's 0-based)
null_vector[5] = 1

# Print the vector
print(null_vector)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


**#### 7. Create a vector with values ranging from 20 to 59


In [9]:
import numpy as np

# Create a vector with values ranging from 20 to 59
vector = np.arange(20, 60)

# Print the vector
print(vector)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]


**#### 8. Reverse a vector (first element becomes last) (★☆☆)
`💡hint: array[::-1]`**

In [10]:
import numpy as np

# Create a sample vector
vector = np.arange(10)
print("Original vector:", vector)

# Reverse the vector
reversed_vector = vector[::-1]

# Print the reversed vector
print("Reversed vector:", reversed_vector)

Original vector: [0 1 2 3 4 5 6 7 8 9]
Reversed vector: [9 8 7 6 5 4 3 2 1 0]


**#### 9. Create a 3x3 matrix with values ranging from 12 to 20 (★☆☆)
`💡hint: reshape`**

In [11]:
import numpy as np

# Create a 1D array with values from 12 to 20
array_1d = np.arange(12, 21)

# Reshape the 1D array into a 3x3 matrix
matrix_3x3 = array_1d.reshape(3, 3)

# Print the matrix
print(matrix_3x3)

[[12 13 14]
 [15 16 17]
 [18 19 20]]


**#### 10. Find indices of non-zero elements from [3,7,0,0,9,0] (★☆☆)
`💡hint: np.nonzero`**

In [12]:
import numpy as np

# Define the array
my_array = np.array([3, 7, 0, 0, 9, 0])

# Find the indices of non-zero elements
nonzero_indices = np.nonzero(my_array)

# Print the indices
print(nonzero_indices)

(array([0, 1, 4]),)


#### 11. Create a 4x4 identity matrix (★☆☆)
`💡hint: np.eye`

In [13]:
import numpy as np

# Create a 4x4 identity matrix
identity_matrix = np.eye(4)

# Print the identity matrix
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


#### 12. Create a 2x2x2 array with random values (★☆☆)
`💡hint: np.random.random`

In [14]:
import numpy as np

# Create a 2x2x2 array with random values
random_array = np.random.random((2, 2, 2))

# Print the array
print(random_array)

[[[0.85101383 0.54111465]
  [0.99297746 0.91633016]]

 [[0.50605425 0.18732862]
  [0.19986396 0.29580978]]]


#### 13. Create a 9x9 array with random values and find the minimum and maximum values (★☆☆)
`💡hint: min, max`

In [15]:
import numpy as np

# Create a 9x9 array with random values
random_array = np.random.random((9, 9))

# Find the minimum value
min_value = random_array.min()

# Find the maximum value
max_value = random_array.max()

# Print the array and the min/max values
print("The 9x9 random array:")
print(random_array)
print(f"\nMinimum value: {min_value}")
print(f"Maximum value: {max_value}")

The 9x9 random array:
[[0.6946557  0.62788142 0.37582147 0.9436388  0.45804646 0.5287036
  0.27594718 0.70108219 0.55656842]
 [0.45581136 0.42416291 0.21541329 0.90863521 0.3320524  0.99171361
  0.69070165 0.39700939 0.21047055]
 [0.1399716  0.75706852 0.06515355 0.49122215 0.91248251 0.460984
  0.9249601  0.05480174 0.72575528]
 [0.99270726 0.3484503  0.51637407 0.95739395 0.63202241 0.55751913
  0.16995439 0.18406073 0.6958628 ]
 [0.71269384 0.9997442  0.56710566 0.17417542 0.60171484 0.60470047
  0.21844735 0.57870009 0.7536039 ]
 [0.70864534 0.38500146 0.77063593 0.49571731 0.75706644 0.03952265
  0.12764069 0.42790756 0.13788612]
 [0.70358081 0.28385812 0.66522297 0.84160044 0.49421042 0.51724906
  0.44811717 0.11224041 0.53687729]
 [0.0748964  0.55795581 0.68702664 0.15408375 0.31774023 0.80235139
  0.77620062 0.14093195 0.36713116]
 [0.70619212 0.85002603 0.02226581 0.09650453 0.07704051 0.24738984
  0.90431742 0.2122265  0.37527789]]

Minimum value: 0.022265808891662853
Maximum

#### 14. Create a random vector of size 20 and find the mean value (★☆☆)
`💡hint: mean`

In [16]:
import numpy as np

# Create a random vector of size 20
random_vector = np.random.rand(20)

# Find the mean value
mean_value = random_vector.mean()

# Print the vector and its mean
print("The random vector:")
print(random_vector)
print(f"\nMean value: {mean_value}")

The random vector:
[0.39651603 0.36997033 0.82015857 0.06148582 0.46143269 0.12531617
 0.37035263 0.76734463 0.5339177  0.97867642 0.78309112 0.40037892
 0.69236131 0.24826672 0.01814246 0.35148872 0.21822577 0.57749647
 0.74912186 0.50387546]

Mean value: 0.4713809901371392


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
`💡hint: array[1:-1, 1:-1]`

In [17]:
import numpy as np

# Define the size of the array (e.g., 5x5)
size = 5

# Create an array filled with 1s
my_array = np.ones((size, size))

# Set the inner part to 0s using slicing
my_array[1:-1, 1:-1] = 0

# Print the array
print(my_array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)
`💡hint: np.pad`

In [18]:
import numpy as np

# Create a sample array
my_array = np.ones((3, 3))
print("Original array:")
print(my_array)

# Add a border of 0s around the array
# The 'pad_width' parameter specifies the number of values padded to the edges
# The 'mode' parameter specifies the type of padding, 'constant' fills with a constant value
# The 'constant_values' parameter specifies the value to use for constant padding
padded_array = np.pad(my_array, pad_width=1, mode='constant', constant_values=0)

print("\nArray with border:")
print(padded_array)

Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Array with border:
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```
`💡hint: NaN = not a number, inf = infinity`

In [19]:
import numpy as np

print(f"0 * np.nan: {0 * np.nan}")
print(f"np.nan == np.nan: {np.nan == np.nan}")
print(f"np.inf > np.nan: {np.inf > np.nan}")
print(f"np.nan - np.nan: {np.nan - np.nan}")
print(f"np.nan in set([np.nan]): {np.nan in set([np.nan])}")
print(f"0.7 == 7 * 0.1: {0.7 == 7 * 0.1}")

0 * np.nan: nan
np.nan == np.nan: False
np.inf > np.nan: False
np.nan - np.nan: nan
np.nan in set([np.nan]): True
0.7 == 7 * 0.1: False


#### 18. Create a 6x6 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
`💡hint: np.diag`


In [20]:
import numpy as np

# Create the values for the diagonal
diagonal_values = np.array([1, 2, 3, 4])

# Create a 6x6 matrix with these values on the diagonal just below the main one (k=-1)
matrix = np.diag(diagonal_values, k=-1)

# Print the matrix
print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 6x6 matrix and fill it with a checkerboard pattern (★☆☆)
`💡hint: array[::2]`

In [21]:
import numpy as np

# Create a 6x6 matrix initialized with zeros
checkerboard = np.zeros((6, 6), dtype=int)

# Fill with a checkerboard pattern using slicing
checkerboard[::2, ::2] = 1
checkerboard[1::2, 1::2] = 1

# Print the checkerboard matrix
print(checkerboard)

[[1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]]


#### 20. Consider a (8,9,10) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
`💡hint: np.unravel_index`

In [22]:
import numpy as np

# Define the shape of the array
shape = (8, 9, 10)

# The index of the 100th element in the flattened array (0-based)
flat_index = 99

# Use np.unravel_index to get the multi-dimensional index
index_3d = np.unravel_index(flat_index, shape)

# Print the index
print(f"The index of the 100th element in an {shape} array is: {index_3d}")

The index of the 100th element in an (8, 9, 10) array is: (np.int64(1), np.int64(0), np.int64(9))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
`💡hint: np.tile`

In [23]:
import numpy as np

# Create a small 2x2 checkerboard pattern
checkerboard_pattern = np.array([[0, 1],
                                 [1, 0]])

# Use np.tile to repeat the pattern to create an 8x8 checkerboard
checkerboard_matrix = np.tile(checkerboard_pattern, (4, 4))

# Print the resulting matrix
print(checkerboard_matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 6x6 random matrix (★☆☆)
`💡hint: (x -mean)/std`


In [24]:
import numpy as np

# Create a 6x6 random matrix
random_matrix = np.random.rand(6, 6)
print("Original random matrix:")
print(random_matrix)

# Calculate the mean and standard deviation of the matrix
mean_value = random_matrix.mean()
std_dev = random_matrix.std()

# Normalize the matrix using the formula (x - mean) / std
normalized_matrix = (random_matrix - mean_value) / std_dev

print("\nNormalized matrix:")
print(normalized_matrix)

Original random matrix:
[[4.96717521e-01 1.93653898e-01 7.48195219e-01 7.61504633e-01
  2.87437720e-01 2.03737761e-01]
 [8.27810837e-01 6.95299223e-01 4.12287307e-01 1.30459305e-01
  3.39690752e-03 8.94714627e-01]
 [3.75808124e-01 5.76399658e-01 1.86621902e-02 8.49321043e-01
  2.40819353e-01 5.78543421e-02]
 [8.39619945e-01 6.60762463e-01 2.99053020e-01 4.01424618e-01
  5.15977906e-01 3.19011876e-02]
 [5.20535666e-01 1.80448523e-01 7.68285046e-01 2.67065589e-01
  7.79082154e-01 4.05591846e-01]
 [8.27846973e-01 4.17226100e-01 4.74429534e-01 4.33151415e-04
  6.13759521e-01 5.69647818e-02]]

Normalized matrix:
[[ 0.20189533 -0.8740048   1.09466129  1.14191077 -0.54106472 -0.83820627]
 [ 1.3773031   0.90687626 -0.09783869 -1.09835066 -1.54943234  1.61481691]
 [-0.22734271  0.48477329 -1.49523937  1.45366606 -0.70656365 -1.35610409]
 [ 1.41922638  0.784268   -0.49982947 -0.13640211  0.27027123 -1.44823986]
 [ 0.28645165 -0.92088493  1.16598178 -0.61338741  1.20431238 -0.12160811]
 [ 1.37743

#### 23. find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements. (★☆☆)

In [25]:
import numpy as np

# Create a sample array
my_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Number of elements
num_elements = my_array.size

# Length of one array element in bytes
element_size = my_array.itemsize

# Total bytes consumed by the elements
total_bytes = my_array.nbytes

print("Sample array:")
print(my_array)
print(f"\nNumber of elements: {num_elements}")
print(f"Length of one array element (bytes): {element_size}")
print(f"Total bytes consumed by elements: {total_bytes}")

Sample array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Number of elements: 12
Length of one array element (bytes): 8
Total bytes consumed by elements: 96


#### 24. Multiply a 6x3 matrix by a 3x4 matrix (real matrix product) (★☆☆)
`💡hint: np.dot` or `np.ones`

In [26]:
import numpy as np

# Create a 6x3 matrix (e.g., with random values)
matrix_a = np.random.rand(6, 3)
print("Matrix A (6x3):")
print(matrix_a)

# Create a 3x4 matrix (e.g., with random values)
matrix_b = np.random.rand(3, 4)
print("\nMatrix B (3x4):")
print(matrix_b)

# Multiply the matrices using np.dot()
# The result will be a 6x4 matrix
matrix_product = np.dot(matrix_a, matrix_b)

print("\nMatrix Product (A * B, 6x4):")
print(matrix_product)

Matrix A (6x3):
[[0.05759585 0.82259372 0.77168508]
 [0.22233251 0.27688678 0.63940668]
 [0.65442815 0.53893371 0.95306526]
 [0.30330457 0.76157417 0.6091695 ]
 [0.31827676 0.99359166 0.60000669]
 [0.17298577 0.49817814 0.64953511]]

Matrix B (3x4):
[[0.19935289 0.29578937 0.54029385 0.11557851]
 [0.87725014 0.98738147 0.06940885 0.74257724]
 [0.18721153 0.93721168 0.25993449 0.00903559]]

Matrix Product (A * B, 6x4):
[[0.8775707  1.55248231 0.28880154 0.62446885]
 [0.4069259  0.93841588 0.30554713 0.2370841 ]
 [0.78166662 1.61892995 0.63872481 0.48444925]
 [0.84259925 1.41259927 0.37507775 0.60608735]
 [1.04740599 1.63753016 0.39688947 0.78002593]
 [0.59311252 1.15181111 0.2968777  0.39579811]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)
`💡hint: >, <`

In [27]:
import numpy as np

# Create a sample 1D array
my_array = np.arange(10)
print("Original array:", my_array)

# Create a boolean mask for elements between 3 and 8 (exclusive)
mask = (my_array > 3) & (my_array < 8)

# Negate the elements in place using the mask
my_array[mask] = -my_array[mask]

# Print the modified array
print("Array after negating elements between 3 and 8:", my_array)

Original array: [0 1 2 3 4 5 6 7 8 9]
Array after negating elements between 3 and 8: [ 0  1  2  3 -4 -5 -6 -7  8  9]


#### 26. What is the output of the following script? (★☆☆)
```python

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [28]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Write a Python program compare two arrays using numpy (★☆☆)
```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [29]:
import numpy as np

# Define the two arrays
a = np.array([1, 2])
b = np.array([4, 5])

print(f"Array a: {a}")
print(f"Array b: {b}")

# Perform element-wise comparisons
print(f"a > b \n{a > b}")
print(f"a >= b \n{a >= b}")
print(f"a < b \n{a < b}")
print(f"a <= b \n{a <= b}")

Array a: [1 2]
Array b: [4 5]
a > b 
[False False]
a >= b 
[False False]
a < b 
[ True  True]
a <= b 
[ True  True]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```
Consider an integer vector a
```python
a**a
a << a >> 2
a <- a
1j*a
a/1/1
a<a>a
```

In [30]:
import numpy as np

# Evaluate the first set of expressions
print(f"np.array(0) / np.array(0): {np.array(0) / np.array(0)}")
print(f"np.array(0) // np.array(0): {np.array(0) // np.array(0)}")
print(f"np.array([np.nan]).astype(int).astype(float): {np.array([np.nan]).astype(int).astype(float)}")

# Define an integer vector a for the second set of expressions
a = np.arange(5) # Example integer vector

print(f"\nConsidering integer vector a: {a}")
print(f"a**a: {a**a}")
print(f"a << a >> 2: {a << a >> 2}")
print(f"a <- a: {a <- a}") # This is a comparison: a is less than -a
print(f"1j*a: {1j*a}")
print(f"a/1/1: {a/1/1}")
# The last expression 'a<a>a' is not valid Python/NumPy syntax.
# It might be a typo or represent a concept not directly translatable to a single expression.
# I will skip this last expression as it is syntactically incorrect.

np.array(0) / np.array(0): nan
np.array(0) // np.array(0): 0
np.array([np.nan]).astype(int).astype(float): [-9.22337204e+18]

Considering integer vector a: [0 1 2 3 4]
a**a: [  1   1   4  27 256]
a << a >> 2: [ 0  0  2  6 16]
a <- a: [False False False False False]
1j*a: [0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
a/1/1: [0. 1. 2. 3. 4.]


/tmp/ipython-input-1453930898.py:4: RuntimeWarning: invalid value encountered in divide
  print(f"np.array(0) / np.array(0): {np.array(0) / np.array(0)}")
/tmp/ipython-input-1453930898.py:5: RuntimeWarning: divide by zero encountered in floor_divide
  print(f"np.array(0) // np.array(0): {np.array(0) // np.array(0)}")
/tmp/ipython-input-1453930898.py:6: RuntimeWarning: invalid value encountered in cast
  print(f"np.array([np.nan]).astype(int).astype(float): {np.array([np.nan]).astype(int).astype(float)}")


#### 29. How to round away from zero a float array ? (★☆☆)
`💡hint: np.uniform, np.copysign, np.ceil, np.abs, np.where`

In [31]:
import numpy as np

# Create a sample float array
float_array = np.array([-3.2, -1.8, 0.5, 2.1, 4.7])
print("Original array:", float_array)

# Round away from zero
# Take the absolute value, apply ceil, and then copy the original sign
rounded_array = np.copysign(np.ceil(np.abs(float_array)), float_array)

# Print the rounded array
print("Rounded away from zero:", rounded_array)

Original array: [-3.2 -1.8  0.5  2.1  4.7]
Rounded away from zero: [-4. -2.  1.  3.  5.]


#### 30. How to find common values between two arrays? (★☆☆)
`💡hint: np.intersect1d`

In [32]:
import numpy as np

# Create two sample arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])

# Find the common values
common_values = np.intersect1d(array1, array2)

# Print the common values
print("Array 1:", array1)
print("Array 2:", array2)
print("Common values:", common_values)

Array 1: [1 2 3 4 5]
Array 2: [3 4 5 6 7]
Common values: [3 4 5]
